<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="Aditya" failures="2" tests="2" name="Default test(failed)" time="8.188" errors="0" timestamp="2025-07-11T12:35:19 IST">
  <testcase classname="m_Listners.e_RunFailedTC" name="ceateInvoice_Test" time="1.6">
    <failure type="java.lang.AssertionError" message="expected [Login] but found [Admin123@ Administrator1 - Home - vtiger CRM 5 - Commercial Open Source CRM]">
      <![CDATA[java.lang.AssertionError: expected [Login] but found [Admin123@ Administrator1 - Home - vtiger CRM 5 - Commercial Open Source CRM]
at m_Listners.e_RunFailedTC.ceateInvoice_Test(e_RunFailedTC.java:18)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- ceateInvoice_Test -->
  <testcase classname="m_Listners.e_RunFailedTC" name="ceateContact_Test" time="0.01">
    <failure type="java.lang.AssertionError" message="expected [Contact] but found [Admin123@ Administrator1 - Home - vtiger CRM 5 - Commercial Open Source CRM]">
      <![CDATA[java.lang.AssertionError: expected [Contact] but found [Admin123@ Administrator1 - Home - vtiger CRM 5 - Commercial Open Source CRM]
at m_Listners.e_RunFailedTC.ceateContact_Test(e_RunFailedTC.java:44)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- ceateContact_Test -->
  <testcase classname="m_Listners.e_RunFailedTC" name="createInvoiceWithContact_Test" time="0.0">
    <ignored/>
  </testcase> <!-- createInvoiceWithContact_Test -->
  <testcase classname="m_Listners.e_RunFailedTC" name="createContactWithEmail_Test" time="0.0">
    <ignored/>
  </testcase> <!-- createContactWithEmail_Test -->
</testsuite> <!-- Default test(failed) -->
